lib/thinking_sphinx/active_record/attribute/sphinx_presenter.rb, spec/thinking_sphinx/active_record/sql_source_spec.rb
Sphinx 2.1 added the `sql_attr_json` type, which is not currently supported when generating a TS configuration file. This change just adds the type so that it can be specified in an index.
(I'm not sure if there are more tests that I should have added, so let me know if I missed something)
=> Add JSON as a Sphinx type

lib/thinking_sphinx/rake_interface.rb, lib/thinking_sphinx/tasks.rb
Port of #284 to the current version of Thinking Sphinx.
Useful for development when using Foreman to start all the services.
Example usage:
rake ts:start NODETACH=true
=> Allow for NODETACH option when running `rake ts:start`

lib/thinking_sphinx/active_record/sql_source/template.rb, lib/thinking_sphinx/middlewares/active_record_translator.rb, spec/thinking_sphinx/active_record/sql_source_spec.rb, spec/thinking_sphinx/middlewares/active_record_translator_spec.rb
Most of the time the attached database will have a primary key defined - however I had a case where there was a large database, with an index marked as primary but not actually an index called PRIMARY. Because the database was being constantly added to it wasn't feasible to reindex (which requires locking).
I should have been able to specify the primary index in the configuration but this didn't filter through to all parts of the code.
As seen [here](https://github.com/pat/thinking-sphinx/blob/master/lib/thinking_sphinx/active_record/index.rb#L66) the configuration value should be used first, followed by the model/database value, and finally just use :id if neither of the other two exist. The attached changes just use this logic in the two other places it seemed to be missing.
=> Allow primary key to be specified in configuration and not in model

lib/thinking_sphinx/middlewares/sphinxql.rb
sphinx now support passing a seed to order `rand()`
but it has to be passed as a separate option so it has been added to
the SELECT_OPTIONS list
I'm not sure if a test is needed for this I looked for one for `comment` and wasn't able to find it
thanks!
[sphinx docs on rand seed](http://sphinxsearch.com/docs/current/sphinxql-select.html)
=> add rand_seed to SELECT_OPTIONS

lib/thinking_sphinx/active_record/association_proxy/attribute_finder.rb, lib/thinking_sphinx/active_record/callbacks/update_callbacks.rb, lib/thinking_sphinx/index_set.rb, lib/thinking_sphinx/middlewares/sphinxql.rb
In our app, IndexSet#references is called 54 times each time a model is saved.  This calls ActiveSupport's `underscore` method, which is relatively expensive and is responsible for a large chunk of object allocations.
This PR moves all instances of `klass.name.underscore.to_sym` to a common `IndexSet.reference_name` method, then caches the result.   WDYT?
=> Reduce allocations in ActiveRecord callbacks

lib/thinking_sphinx/middlewares/stale_id_checker.rb, lib/thinking_sphinx/middlewares/stale_id_filter.rb, lib/thinking_sphinx/search/stale_ids_exception.rb, spec/thinking_sphinx/middlewares/stale_id_checker_spec.rb, spec/thinking_sphinx/middlewares/stale_id_filter_spec.rb
Prior to this, BatchedSearches with multiple contexts would append stale ids to the first context, rather than the context which was actually missing them, and so the retried attempts would also fail.  WDYT?
=> Fix StaleId handling with multiple contexts

lib/thinking_sphinx/real_time/populator.rb, lib/thinking_sphinx/real_time/transcriber.rb, spec/thinking_sphinx/real_time/callbacks/real_time_callbacks_spec.rb
Doing a generate on a large dataset takes a long time. While looking into improvements, I noticed the actual sphinx query is a single insert/replace for every record, which would lead to lots and lots of commands being run. I've switched it to use find_in_batches which will yield batches of instances to the transcriber which can then utilize the fact that the Riddle Insert will handle inserting multiple records in one command.
I didn't really see any tests handling this case, nor many for the transcriber, so I just got the existing tests to work by having them expect an array of values (even though it was just one value set). I'm sure there should be more/better tests, but I'm not too familiar with the test suite to write it all up.
The end goal is that the command that gets run by the …
=> Change from find_each to find_in_batches to allow a bulk replace into command

lib/thinking_sphinx/middlewares/active_record_translator.rb
After struggling to find why this configuration wasn't being applied, I found that it was loading from a symbol, meanwhile thinking_sphinx.yml's loaded variables were being treated as strings.
=> configuration.settings are always strings, not symbols

lib/thinking_sphinx/rake_interface.rb, lib/thinking_sphinx/tasks.rb, spec/thinking_sphinx/rake_interface_spec.rb
Some of our indices take a loooong time to generate so we don't want to have to always generate them all
Usage `rake ts:generate INDEX_FILTER=user_core`
=> Be able to generate a single real time index

lib/thinking_sphinx/errors.rb
In SUSE's SLE-11 MySQL package, it can happen that the MySQL server responds with "Lost connection to MySQL server". This should be handled in the code.
We're currently patching this manually during package building: https://build.opensuse.org/package/view_file/devel:languages:ruby:extensions/rubygem-thinking-sphinx/SLE-11-mysql-error.patch?expand=1
It would be nice to get this in your code base, so we do not need this patch anymore to support SLES-11 (SUSE Linux Enterprise Server 11)
=> Fix SLE-11 MySQL error handling

lib/thinking_sphinx/active_record/sql_source.rb
@pat 
On Octopus 0.9.x the `model.connection` method doesn't return a normal `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter` (or whatever is configured). Instead a `Octopus::ProxyConfig` is returned which proxies a lot of the functionality.
In this case, `@config` instance variable is not guaranteed to exist. We need to check for this.
Let me know if you have a better idea for addressing this problem.
=> Support Octopus gem's Octopus::ProxyConfig

lib/thinking_sphinx/middlewares/active_record_translator.rb, spec/thinking_sphinx/middlewares/active_record_translator_spec.rb
When multiple indices defined in search it becomes almost impossible to define sql includes. Different models has different relations usually
```ruby
class City < ApplicationRecord
has_one :overall_stat
belongs_to :country
end
class Country < ApplicationRecord
has_many :cities
end
```
This woudn't work
```ruby
ThinkingSphinx.search("*", indices: %w(country_core city_core), sql: {include: [:overall_stat, :country]})
```
I suggest to define ```:sql``` option in the following maner (with fallback to previous variant):
```ruby
ThinkingSphinx.search("*", indices: %w(country_core city_core), sql: {'City' => {include: [:overall_stat, :country]}})
```
=> sql_options defined per model

lib/thinking_sphinx/scopes.rb, spec/thinking_sphinx/scopes_spec.rb
I ran into problems trying to stub out sphinx scopes with rspec:
```ruby
class Post
sphinx_scope :public_posts, -> { { with: {public_read: true } }
end
allow(Post).to receive(:public_posts).and_return(double('sphinx-results'))
``` 
which raises "Post does not implement: public_posts".  WDYT to this fix?
=> Fix respond_to with scopes

lib/thinking_sphinx/active_record/source_joins.rb, spec/acceptance/specifying_sql_spec.rb
Any fields that have their source set to :query will be collected
separately by sphinx. As such these fields do not need to be included
in the overal joins statement. Including them may seem harmless but
may lead to considerable performance issues when indexing. Consider
the following data model:
post
\- document - document_content
\- comment
\- document - document_content
The document_content table would contain pre-parsed text content of
documents where the content of the blobs could easily reach 100kb or
more. If such a document is referenced in a popular discussion this
document data is included many times as part of the joins structure,
leading to massive resource consumption during indexing. All of these
resource consumption is also waisted because sphinx will not even
consider the …
=> Skip source=query columns in joins

lib/thinking_sphinx/core/index.rb
I have spend about 3 hours debugging a test instance to identify this problem. Although it is not a major issue I think
it could save a lot of time.
Summary is the following:
1. Table does not exists
2. rake ts:index returns a very strange error connected with configuration
3. There is nothing wrong in the configuration and the same configuration is working on other app instances.
4. For this particulare app instance a certain table is missing.
5. Because of the missing table no configuration could be generated and the error is that there is something wrong with the index
6. Contrary there is nothing wrong with the index. It is just not existing, because it can not be generated and the reason why it can not be generated is difficult to identify at first.
Details are the following.
When …
=> [Debug] Logging info that table does not exist for a model

v4/installing_thinking_sphinx/ts4.md
After getting set up with Thinking Sphinx, as I was about to commit my changes, I noticed the `db/sphinx` directory and files.
I had not come across an explanation of these files in the setup process, but they looked to me like data files in use by Sphinx.
I contacted @pat to ask if they should be `gitignored` and he recommended that they should be, along with the `config/ENV.sphinx.conf` files.
I've added some instructions to the Installing Thinking Sphinx step for the latest Rails version. This seemed intuitive to my use case, but if this is relevant to other platforms, maybe it should be in a more generic/visible place.
Thanks @pat
Luke
=> Explain what should be gitignored during setup

v4/excerpts.md
This was a temporary gotcha for me when getting started with the `Excerpter`. I wasn't targeting my index correctly because I was using `item`, rather that `item_core`.
At the moment the explanation I've added is a bit arbitrary, it would be nice to explain why you add `_core` to the index name (maybe in the Indexing docs), but this small addition would have helped me I think.
=> Explain how to reference the index with _core when Initializing Excerpter

lib/thinking_sphinx/active_record/callbacks/delete_callbacks.rb, lib/thinking_sphinx/active_record/callbacks/delta_callbacks.rb, lib/thinking_sphinx/index_set.rb, spec/thinking_sphinx/index_set_spec.rb
Prompted by discussions in #1166, this PR changes the IndexSet class to accept `:instances` alongside the `:classes` option, which could allow custom subclasses of IndexSet to filter returned indices to a subset as determined by the provided instances.
In particular, if you're sharding your indices, you can return just the specific shard of indices for the instance, rather than _all_ shards:
```ruby
class IndexSet < ThinkingSphinx::IndexSet
private
def indices
return super if instances.empty?
super.select do |index|
instances.any? { |instance| index.name[/_#{instance.shard_id}_$/] }
end
end
end
ThinkingSphinx::Configuration.instance.index_set_class = IndexSet
```
While it's not necessary moving forward, I'm still passing through the `:classes` option for anyone who's got a custom IndexSet …
=> Use instances for index filtering from callbacks.

lib/thinking_sphinx/active_record/base.rb, lib/thinking_sphinx/callbacks.rb, lib/thinking_sphinx/callbacks/appender.rb, spec/internal/app/models/admin/person.rb, spec/internal/app/models/album.rb, spec/internal/app/models/animal.rb, spec/internal/app/models/article.rb, spec/internal/app/models/bird.rb, spec/internal/app/models/book.rb, spec/internal/app/models/car.rb, spec/internal/app/models/city.rb, spec/internal/app/models/product.rb, spec/internal/app/models/tee.rb, spec/internal/app/models/user.rb
As discussed in #1173 and initially prompted by discussions in #1158, this commit removes the automatic insertion of callbacks into every single ActiveRecord model, and instead expects them to be explicitly added to the models that are indexed. The syntax is as follows:
```ruby
ThinkingSphinx::Callbacks.append(model, reference, options, &block)
```
Given this code will almost always be invoked from within an ActiveRecord model, the `model` argument will be `self`.
The `reference` is optional, but should match the first argument of the index in question. e.g. it’ll likely be the model name, lowercase and underscored, as a symbol. If the model is namespaced, though, this should be a string, with slashes to indicate the namespacing (like how a namespaced index is defined).
The options are …
=> Switch to explicitly-added callbacks.

.circleci/config.yml, Appraisals, bin/loadsphinx, spec/acceptance/geosearching_spec.rb, spec/acceptance/support/sphinx_helpers.rb, spec/internal/config/database.yml
Travis sadly no longer supports open-source projects for free. GitHub Actions seemed promising, but there is no ability to retry single/failed jobs. CircleCI works well enough with a bit of wrangling (using Debian rather than Ubuntu Sphinx/Manticore releases).
=> Use CircleCI instead of Travis, and confirm Rails 6.1 support.

lib/thinking_sphinx/real_time/index/template.rb, lib/thinking_sphinx/real_time/populator.rb, lib/thinking_sphinx/real_time/transcriber.rb, lib/thinking_sphinx/real_time/translator.rb, lib/thinking_sphinx/settings.rb, spec/thinking_sphinx/real_time/index_spec.rb
This PR adds a new internal attribute - `sphinx_updated_at` - to real-time indices, and sets that with the current timestamp whenever that record is inserted or updated. And then, when a reindex happens, any record that has not changed since the reindexing began is removed - as it's not in the known dataset. Likely, it was deleted but the callbacks failed for some reason.
The advantage of this is that running `ts:index` will remove any records that are no longer indexed - thus keeping index sizes to what they should be, avoiding any bloat that may crop up from situations where records haven't been removed (bulk deletions, for example) - and this is done without the need for deleting _all_ records to begin with (the behaviour of `ts:rebuild`).
This is currently only enabled with …
=> Clean up orphaned real-time records after reindexing.

lib/thinking_sphinx.rb, lib/thinking_sphinx/railtie.rb
If ThinkingSphinx requires ActiveRecord on load, then setting configuration in applications' initializers with have no effect (eg
`Rails.application.config.active_record.has_many_inversing`).
Instead, ActiveRecord should be deferred to the end of initialization using the Railtie. WDYT to something like this?
=> Don't load ActiveRecord during rails initialization

lib/thinking_sphinx/active_record/callbacks/delete_callbacks.rb, lib/thinking_sphinx/callbacks/appender.rb, spec/acceptance/sql_deltas_spec.rb, spec/thinking_sphinx/active_record/index_spec.rb
This also applies to deletions generally (no matter what type of indices are in play).
This was prompted by feedback from @krauselukas in #1203. It certainly makes more sense to wait until the database changes are fully committed before we update Sphinx, so I feel like this switch is a smart one.
=> Use after_commit callbacks for real-time changes.

lib/thinking_sphinx/railtie.rb
Rails 7 uses zeitwerk exclusively: https://weblog.rubyonrails.org/2021/9/15/Rails-7-0-alpha-1-released. So, checking for the autoloader breaks as it is no longer defined in the config.
=> support rails 7

lib/thinking_sphinx/masks/pagination_mask.rb
under manticore 4.2.0 the pagination doesn't work because the search function returns total_pages = 1 every time
```
2.7.4 :001 > @books = Book.search('test', per_page: 5)
2.7.4 :002 > @books.total_count
=> 220 
2.7.4 :003 > @books.total_pages
=> 1 
```
search.meta => {"total"=>"5", "total_found"=>"220", "time"=>"0.000", "keyword[0]"=>"test", "docs[0]"=>"220", "hits[0]"=>"302"}
i think my fix solves this problem and doesn't generate another :)
=> fixes a weird bug: search.total_pages is always 1

lib/thinking_sphinx/settings.rb
Ruby 3.1 comes with Psych 4 which has some breaking changes to `YAML.load` [See this ruby issue](https://bugs.ruby-lang.org/issues/17866). 
I had been using a `config/thinking_sphinx.yml` file with aliases, which failed to load after I upgraded  a rails app to ruby 3.1. Here's an example configuration:
``` yaml
defaults: &defaults
min_word_len: 2
charset_table: "0..9, A..Z->a..z, _, a..z, \
U+410..U+42F->U+430..U+44F, U+430..U+44F"
test:
<<: *defaults
mysql41: 9313
development:
<<: *defaults
production:
<<: *defaults
address: 10.0.0.1
```
Such a configuration works with ruby versions prior to 3.1.
=> Use YAML.unsafe_load to load configuration file

lib/thinking_sphinx/guard/file.rb
Replaced deprecated File.exist?
=> Ruby 3 - File.exists? is deprecated; use File.exist? instead

.circleci/config.yml, .github/actions/test/action.yml, .github/workflows/ci.yml, bin/loadsphinx
Now that GitHub Actions allows for retrying of failed jobs only, the switch is viable. That said, we’re going to keep using Circle CI for Sphinx 2.2.11, as GitHub no longer supports Ubuntu 16 (and Sphinx v2.2 doesn’t work on anything newer).
The added advantage of this is that we can keep Ruby v2.4, Rails v4.2, and Bundler v1 to just the Circle CI build, and v2.5+, v5.0+, and v2+ respectively on GitHub. Also, I've split the Manticore and Sphinx sections up, because Manticore requires MySQL v8, whereas we probably still want to use v5.7 with Sphinx (certainly for v2.2.11).
=> Shift most tests to GitHub Actions

lib/thinking_sphinx/commands/clear_real_time.rb, lib/thinking_sphinx/settings.rb, spec/support/sphinx_yaml_helpers.rb, spec/thinking_sphinx/commands/clear_real_time_spec.rb, spec/thinking_sphinx/commands/clear_sql_spec.rb, spec/thinking_sphinx/configuration_spec.rb
All the hard work has been done by @graaff on #1232 - but my poorly structured tests were getting in the way. My added commit fixes that problem, and CI's all happy. Thanks @graaff!
=> Finish replacing deprecated File.exists? with File.exist?

.github/workflows/ci.yml
Which version you want to support is up to you, but given ruby 2.6 is no longer supported by the ruby team, maybe it's time to drop it from CI?
The `matrix.exclude` option is getting kind of verbose - wondered if there was a shorter alternative with `matrix.include` but not sure it's possible.
=> Test ruby 3.1 & 3.2, drop 2.5 & 2.6

.github/workflows/ci.yml, bin/loadsphinx
This updates Github CI to include sphinx 2.2.11, and updates the list of supported rubies to test manticore against.
Sphinx 2 does work ok, AFAICT, though a few times it hit the 12 minute timeout. Re-running the action fixed it.
I did experiment with removing the extra `sleep` calls we use with `ENV['CI']` - seemed like the manticore tests were fine with it, but it did cause a few extra sphinx failures.
After this update, we have 60 manticore test runs, and 45 sphinx, which seems quite a lot. Is it worth thinking about dropping Rails 5.x support? Or at least 5.0 & 5.1 ?
Want me to remove the Travis & CircleCI config, or are they still useful after this?
=> Updating GitHub CI build matrices

lib/thinking_sphinx/settings.rb
Since Manticore 5.0, their default cutoff is the same as the search request’s page size - which helps make search requests faster. The unfortunate trade-off is that it means pagination breaks because we no longer know what the actual total number of results is (Manticore stops counting once the cutoff is reached).
So, at least for now, we’re going to set a default cutoff of 0, which essentially removes that limit. Judging by the CI results, Sphinx is fine with this too.
=> Set a default cutoff for Manticore.

.github/workflows/ci.yml, README.textile, bin/loadsphinx
There are 4.2 and 5.0 releases as well, but they have a bug with facet searches (which wasn’t fixed until now, as there were no 5.1 releases).
=> build: test against Manticore 6.0.

lib/thinking_sphinx/configuration/minimum_fields.rb, spec/thinking_sphinx/configuration/minimum_fields_spec.rb
because of my oversight in #1222 all rt indices lost the `sphinx_internal_class_name` field and this is not correct. In either index type, when single table inheritance is used, then `sphinx_internal_class_name` should be present. Now also added a test for it - to make sure both index types are handled.
=> handle rt and plain indices the same

v3/index.md, v4/index.md, v5/index.md
`http://pat.github.com/riddle` [gives a 404](https://pat.github.com/riddle). I didn't know user sites were ever available at *.github.com. I could've just updated the links to be `pat.github.io/riddle`, but that redirects, so I've just used the destination.
You might have other places to change from `.com` to `.io` - e.g. the repo name and description of https://github.com/pat/pat.github.com
=> Fix links to Riddle in docs homepages

.github/workflows/ci.yml, spec/acceptance/attribute_access_spec.rb, spec/acceptance/excerpts_spec.rb, spec/acceptance/grouping_by_attributes_spec.rb, spec/acceptance/searching_with_filters_spec.rb, spec/acceptance/sorting_search_results_spec.rb, spec/acceptance/sphinx_scopes_spec.rb, spec/internal/app/indices/book_index.rb, spec/internal/app/models/book.rb, spec/internal/db/schema.rb
This should get the CI all green again
* GHA has deprecated the ubuntu 18 runner, so I've updated to 22.
* Manticore has introduced a `year` keyword, which [apparently can't be escaped](https://github.com/manticoresoftware/manticoresearch/issues/1827), so I've renamed `Book#year` in the tests to `Book#publishing_year`
=> Fixing CI tests

.github/workflows/ci.yml, Appraisals, lib/thinking_sphinx/active_record/filter_reflection.rb, lib/thinking_sphinx/active_record/log_subscriber.rb, spec/thinking_sphinx/active_record/callbacks/update_callbacks_spec.rb, spec/thinking_sphinx/active_record/interpreter_spec.rb, spec/thinking_sphinx/excerpter_spec.rb, spec/thinking_sphinx/index_spec.rb, spec/thinking_sphinx/middlewares/sphinxql_spec.rb, spec/thinking_sphinx/panes/excerpts_pane_spec.rb, spec/thinking_sphinx/real_time/interpreter_spec.rb, spec/thinking_sphinx_spec.rb, thinking-sphinx.gemspec
This was going to just be a tiny fix for a LogSubscriber deprecation in Rails 7.1 (https://github.com/pat/thinking-sphinx/commit/cde7554aaf5169ea633015b40992204c53953e2d) but I ran into a few other issues getting the test-suite running.
=> Fixes for Rails 7.1

lib/thinking_sphinx/active_record/base.rb, spec/acceptance/searching_within_a_model_spec.rb
This approach will always add the following methods to ActiveRecord::Base:
* `sphinx_search`
* `sphinx_search_for_ids`
* `sphinx_search_count`
* `sphinx_facets`
And then, if there aren't methods already existing without the `sphinx_` prefix, they're also added:
* `search`
* `search_for_ids`
* `search_count`
* `facets`
This does not remove the possibility that something invoked _after_ Thinking Sphinx will overwrite the `search` method, etc - but at least the `sphinx_`-prefixed versions will always be available.
This addresses #1264 and is an evolution of #1241.
=> Avoid overwriting existing search methods
